# Generated by Django 4.1.1 on 2022-09-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, default='default.png', upload_to='uploads/profile_pictures'),
        ),
    ]
